## src/models/05_1_weighted_expansion_agg.R
# Calculate aggregate counts without fully expanding

# libraries
library(dplyr)
library(tidyr)
library(here)

# load plays_dest (generated by 05_inferdestin_batched.R)
plays_dest <- readRDS(here("data/derived/plays_dest.rds"))

# read lookup of states to know the total number of states
states_lookup <- readRDS(here("data/derived/states_lookup.rds"))
n_states      <- nrow(states_lookup)
all_states    <- seq_len(n_states)  # 1, 2, ..., n_states

# Count how many moves there are for each home state (start_state)
count_by_origin <- plays_dest |>
  group_by(start_state) |>
  summarize(n_plays = n(), .groups = "drop")

# Build aggregate table origin to dest with uniform weight
trans_counts_agg <- count_by_origin |>
  tidyr::crossing(dest_state = all_states) |>
  mutate(total_weight = n_plays * (1 / n_states)) |>
  select(origin_state = start_state, dest_state, total_weight) |>
  filter(total_weight > 0)

# save output
saveRDS(trans_counts_agg, here("data/derived/trans_counts_agg.rds"))
message("05_1_weighted_expansion_agg.R: trans_counts_agg.rdsgenerated correctly.")
