## src/models/train_xgb_dest.R
# Train an XGBoost model to predict the end_state for each pass,
# using sampling to reduce memory usage.

# libraries
library(dplyr)
library(here)
library(xgboost)
library(tidyr)

# load plays.rds generated by run/03_generate_plays.R
plays <- readRDS(here("data/derived/plays.rds"))

# Select only plays with end_state not NA
train_df <- plays %>%
  filter(!is.na(end_state) & start_state != end_state) %>%
  select(start_state, end_state,
         location.x, location.y,
         pass.end_location.x, pass.end_location.y)

# Sample (for example, 50% of the records) to avoid loading everything into memory
set.seed(123)
train_df <- train_df %>% sample_frac(0.5)

# Create basic features: angle and log-distance of the pass
train_features <- train_df %>%
  mutate(
    angle    = atan2(pass.end_location.y - location.y,
                     pass.end_location.x - location.x),
    dist     = sqrt((pass.end_location.x - location.x)^2 +
                      (pass.end_location.y - location.y)^2),
    log_dist = log(dist + 1)
  ) %>%
  select(start_state, angle, log_dist)

# label = end_state
train_labels <- train_df$end_state

# Number of classes = total rows in states_lookup (8×5 grid, 40 classes)
states_lookup <- readRDS(here("data/derived/states_lookup.rds"))
n_states      <- nrow(states_lookup)  # debe ser 40

# Build DMatrix for XGBoost (classes from 0 to n_states−1)
dtrain <- xgb.DMatrix(
  data  = as.matrix(train_features),
  label = train_labels - 1
)

# Define parameters for multiclassification
params <- list(
  objective   = "multi:softprob",
  eval_metric = "mlogloss",
  num_class   = n_states
)

# train model
set.seed(123)
xgb_model <- xgb.train(
  params   = params,
  data     = dtrain,
  nrounds  = 50,
  verbose  = 0
)

# save output
if (!dir.exists(here("models"))) dir.create(here("models"))
xgb.save(xgb_model, fname = here("models/xgb_dest_model.xgb"))
saveRDS(xgb_model, here("models/xgb_dest_model.rds"))
message("train_xgb_dest.R: XGBoost model saved in models/xgb_dest_model.xgb y .rds")
